apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  POSTGRES_DB: bookstore_payment_db
  DB_URL: jdbc:postgresql://postgres-service:5432/bookstore_payment_db
  DB_USERNAME: postgres
  SERVER_PORT: "8082"
  POSTGRES_USER: postgres
  GOOGLE_CLIENT_ID: dummy
  
